on:
  push:
  pull_request:

name: Test Find Jira Issue Refs

jobs:
  test-find-jira-refs:
    name: Find Jira Refs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Find Refs
      id: find
      uses: ./
      with:
        string: Search is performed in this string. GA-250 will be found
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Show issues
      run: echo "Issue ${{ toJSON(steps.find.outputs.issues) }} was found"
